version: '3.1'
services:
  car-dealerships:
    image: 'car-dealerships:latest'
    build: .
    container_name: car-dealerships
    depends_on:
      - cd-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cd-db:5432/car-dealerships
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080

  cd-db:
    image: postgres:14-alpine
    container_name: cd-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=car-dealerships
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
