CREATE TABLE IF NOT EXISTS dealerships
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city        VARCHAR(100)                            NOT NULL,
    rent        INTEGER                                 NOT NULL,
    description VARCHAR(1000)                           NOT NULL,
    square      INTEGER                                 NOT NULL,
    staff       INTEGER                                 NOT NULL,
    CONSTRAINT pk_dealerships PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cars
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model     VARCHAR(100)                            NOT NULL,
    color     VARCHAR(100)                            NOT NULL,
    price     INTEGER                                 NOT NULL,
    max_speed INTEGER                                 NOT NULL,
    dealer_id BIGINT,
    CONSTRAINT pk_car PRIMARY KEY (id),
    CONSTRAINT FK_DEALER_ON_DEALER_ID FOREIGN KEY (dealer_id) REFERENCES dealerships (id)

);

CREATE TABLE IF NOT EXISTS dealerships_cars
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dealer_id BIGINT                                  NOT NULL,
    cars_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_events_compilations PRIMARY KEY (id),
    CONSTRAINT FK_EVENT_ON_EVENT_ID FOREIGN KEY (dealer_id) REFERENCES dealerships (id),
    CONSTRAINT FK_COMPILATION_ON_COMPILATION_ID FOREIGN KEY (cars_id) REFERENCES cars (id)
);

